### PR TITLE
Retarget to net6 and Cake.Common 2.2.

### PR DESCRIPTION
**Pull request by sqeezy**
There were no apparent problems with this update.

### CODE REVIEW

**Comment by sqeezy** [comment]
Fixes #47

**Comment by sqeezy** [comment]
I would also be willing to co-maintain this repo in the future if that helps.

**Comment by taconaut** [comment]
Now that cake 3.0 removed the `DotNetCore` aliases, this change has become required as `Cake.Coverlet` can't be used with Cake 3.0 anymore. See https://github.com/cake-build/cake/discussions/4072
@Romanx would you integrate the changes if we make a PR to migrate to Cake 3.0 or do we have to clone this repo and push a new nuget? I guess you're the owner of the package; I've never pushed to nuget.org but think we'd have to give the package a new name.

**Comment by sqeezy** [comment]
I would very much like to stay inside this project. Maintaing a fork seems like a bad idea in this case.
I can only repeat that me and my company would be happy to support this project and I personally would offer to co-maintain if wanted.

**Comment by Romanx** [comment]
Hey @sqeezy and @taconaut 

Thanks for engaging with this, I started bumping to Cake 2.0.0 awhile back and ended up down the well yak shaving and never found time to get back to this.

I've bumped to the latest version and pushed a new build to nuget, please let me know if you find any issues and i'll try keep on top of this in future.

**Comment by taconaut** [comment]
@Romanx Thanks, works like a charm

**Comment by sqeezy** [comment]
@Romanx Agreed. Sadly dotnet test is broken under 7.0.100 but having Cake.Coverlet on the newest version of Cake is reassuring. I'd like to reiterate that me and my company would be happy to help with maintaining this package.

Thanks!

**Pull request closed without merging**
